### ISSUE TITLE
Module not working out of the box - do not know how to make it work...

### ISSUE THREAD

**Issue by alexionegit** [MSiliunas/Prestashop-GoogleTagManager#6]
Hi,

On PrestaShop v1.7.6 the MSiliunas / Prestashop-GoogleTagManager is not working.

Installs ok
General JS code is being insrted into the page

BUT

{gtmID} is not correct in the script. It is generic, not populated with the value inserted in the PrestaShop Module Configuration.

How to make it work? Could you please post working version?

Thank you!

Alexandru

**Comment by LucasVollebergh** [comment]
Had the same issue. Redownloaded, reinstalled and now it does work for me.
